/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Signup = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });

export const idlService = IDL.Service({
  'addSupporter' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getSignups' : IDL.Func([], [IDL.Vec(Signup)], ['query']),
  'getSupporterCount' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Signup = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    'addSupporter' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getSignups' : IDL.Func([], [IDL.Vec(Signup)], ['query']),
    'getSupporterCount' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };